// flow-typed signature: dbe9f4b2a77b1da2ad2ae6dedef971df
// flow-typed version: <<STUB>>/grid-styled_v^2.0.0-10/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grid-styled'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grid-styled' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grid-styled/dist/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Golden' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Half' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/index' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/propTypes' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Quarter' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/remove-props' {
  declare module.exports: any;
}

declare module 'grid-styled/dist/Third' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Box' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Flex' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Golden' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Grid' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Half' {
  declare module.exports: any;
}

declare module 'grid-styled/src/index' {
  declare module.exports: any;
}

declare module 'grid-styled/src/propTypes' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Quarter' {
  declare module.exports: any;
}

declare module 'grid-styled/src/remove-props' {
  declare module.exports: any;
}

declare module 'grid-styled/src/Third' {
  declare module.exports: any;
}

declare module 'grid-styled/test' {
  declare module.exports: any;
}

declare module 'grid-styled/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grid-styled/dist/Box.js' {
  declare module.exports: $Exports<'grid-styled/dist/Box'>;
}
declare module 'grid-styled/dist/Flex.js' {
  declare module.exports: $Exports<'grid-styled/dist/Flex'>;
}
declare module 'grid-styled/dist/Golden.js' {
  declare module.exports: $Exports<'grid-styled/dist/Golden'>;
}
declare module 'grid-styled/dist/Grid.js' {
  declare module.exports: $Exports<'grid-styled/dist/Grid'>;
}
declare module 'grid-styled/dist/Half.js' {
  declare module.exports: $Exports<'grid-styled/dist/Half'>;
}
declare module 'grid-styled/dist/index.js' {
  declare module.exports: $Exports<'grid-styled/dist/index'>;
}
declare module 'grid-styled/dist/propTypes.js' {
  declare module.exports: $Exports<'grid-styled/dist/propTypes'>;
}
declare module 'grid-styled/dist/Quarter.js' {
  declare module.exports: $Exports<'grid-styled/dist/Quarter'>;
}
declare module 'grid-styled/dist/remove-props.js' {
  declare module.exports: $Exports<'grid-styled/dist/remove-props'>;
}
declare module 'grid-styled/dist/Third.js' {
  declare module.exports: $Exports<'grid-styled/dist/Third'>;
}
declare module 'grid-styled/src/Box.js' {
  declare module.exports: $Exports<'grid-styled/src/Box'>;
}
declare module 'grid-styled/src/Flex.js' {
  declare module.exports: $Exports<'grid-styled/src/Flex'>;
}
declare module 'grid-styled/src/Golden.js' {
  declare module.exports: $Exports<'grid-styled/src/Golden'>;
}
declare module 'grid-styled/src/Grid.js' {
  declare module.exports: $Exports<'grid-styled/src/Grid'>;
}
declare module 'grid-styled/src/Half.js' {
  declare module.exports: $Exports<'grid-styled/src/Half'>;
}
declare module 'grid-styled/src/index.js' {
  declare module.exports: $Exports<'grid-styled/src/index'>;
}
declare module 'grid-styled/src/propTypes.js' {
  declare module.exports: $Exports<'grid-styled/src/propTypes'>;
}
declare module 'grid-styled/src/Quarter.js' {
  declare module.exports: $Exports<'grid-styled/src/Quarter'>;
}
declare module 'grid-styled/src/remove-props.js' {
  declare module.exports: $Exports<'grid-styled/src/remove-props'>;
}
declare module 'grid-styled/src/Third.js' {
  declare module.exports: $Exports<'grid-styled/src/Third'>;
}
declare module 'grid-styled/test.js' {
  declare module.exports: $Exports<'grid-styled/test'>;
}
declare module 'grid-styled/webpack.config.js' {
  declare module.exports: $Exports<'grid-styled/webpack.config'>;
}
