// flow-typed signature: 856acf8350cbec2dbe6920a2886142f6
// flow-typed version: <<STUB>>/@tsuyoshiwada/htmltojsx_v^0.0.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tsuyoshiwada/htmltojsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tsuyoshiwada/htmltojsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tsuyoshiwada/htmltojsx/htmltojsx' {
  declare module.exports: any;
}

declare module '@tsuyoshiwada/htmltojsx/test/htmltojsx.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tsuyoshiwada/htmltojsx/htmltojsx.js' {
  declare module.exports: $Exports<'@tsuyoshiwada/htmltojsx/htmltojsx'>;
}
declare module '@tsuyoshiwada/htmltojsx/test/htmltojsx.spec.js' {
  declare module.exports: $Exports<'@tsuyoshiwada/htmltojsx/test/htmltojsx.spec'>;
}
